[package]
name = "solve"
version = "0.1.0"
authors = ["cosmin-bianu <54325599+cosmin-bianu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
